# Generated by Django 6.0.1 on 2026-01-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='commission',
        ),
        migrations.AddField(
            model_name='availability',
            name='lunch_end',
            field=models.TimeField(blank=True, help_text='Fim do almoço', null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='lunch_start',
            field=models.TimeField(blank=True, help_text='Início do almoço', null=True),
        ),
    ]
