# Generated by Django 6.0.1 on 2026-01-14 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_service_commission_availability_lunch_end_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('buffer_minutes', models.IntegerField(default=5)),
                ('booking_horizon_days', models.IntegerField(default=30)),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.barber'),
        ),
        migrations.AddField(
            model_name='availability',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='api.barber'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='barber',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='api.barber'),
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together={('barber', 'day_of_week')},
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slot', to='api.appointment')),
            ],
            options={
                'indexes': [models.Index(fields=['start_time', 'end_time'], name='api_timeslo_start_t_e123ba_idx')],
            },
        ),
    ]
