# Generated by Django 6.0.1 on 2026-01-14 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_barber_service_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='barber',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.barber'),
            preserve_default=False,
        ),
    ]
