# Generated by Django 6.0.1 on 2026-01-16 03:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_customer_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='email',
        ),
    ]
