# Generated by Django 6.0.1 on 2026-01-17 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_customer_cpf_remove_customer_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='barbers/'),
        ),
    ]
