# Generated by Django 6.0.1 on 2026-01-17 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_barber_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.RemoveField(
            model_name='customer',
            name='last_visit',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='points',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_spent',
        ),
        migrations.CreateModel(
            name='Barbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='barbershops/logos/')),
                ('primary_color', models.CharField(default='#007AFF', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_barbershops', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='appointment',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='barber',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='barbers', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='loyaltyreward',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='loyalty_rewards', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='product',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='service',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='api.barbershop'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('OWNER', 'Dono'), ('BARBER', 'Barbeiro'), ('CLIENT', 'Cliente')], default='CLIENT', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerBarbershop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_visit', models.CharField(default='Primeira vez', max_length=100)),
                ('total_spent', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(blank=True, default='')),
                ('points', models.IntegerField(default=0, help_text='Pontos de fidelidade')),
                ('barbershop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customers', to='api.barbershop')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barbershop_stats', to='api.customer')),
            ],
            options={
                'unique_together': {('customer', 'barbershop')},
            },
        ),
    ]
