# Generated by Django 6.0.1 on 2026-01-17 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_customer_options_remove_customer_last_visit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='banner',
            field=models.ImageField(blank=True, null=True, upload_to='barbershops/banners/'),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
