# Generated by Django 6.0.1 on 2026-01-17 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_barbershop_address_barbershop_banner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api.barbershop'),
        ),
        migrations.AddField(
            model_name='scheduleexception',
            name='barbershop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schedule_exceptions', to='api.barbershop'),
        ),
    ]
