# Generated by Django 6.0.1 on 2026-01-17 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_availability_barbershop_scheduleexception_barbershop'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='instagram',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
