# Generated by Django 6.0.1 on 2026-01-17 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_barbershop_instagram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='availability',
            options={'ordering': ['day_of_week', 'start_time']},
        ),
        migrations.AlterUniqueTogether(
            name='availability',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='availability',
            name='lunch_end',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='lunch_start',
        ),
    ]
