# Generated by Django 5.2.3 on 2026-01-21 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_availability_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='plan',
            field=models.CharField(choices=[('BASIC', 'Básico'), ('TEAM', 'Equipe'), ('PRO', 'IA Pro')], default='BASIC', max_length=10),
        ),
    ]
