# Generated by Django 5.2.3 on 2026-01-21 23:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_barbershop_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('barber', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_availability', to='api.barber')),
                ('barbershop', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_availabilities', to='api.barbershop')),
            ],
            options={
                'ordering': ['date', 'start_time'],
            },
        ),
    ]
