# Generated by Django 5.2.3 on 2026-01-23 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_userprofile_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
