# Generated by Django 5.2.3 on 2026-01-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_barber_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barbershop',
            name='plan',
            field=models.CharField(choices=[('trial', 'Teste Grátis'), ('BASIC', 'Básico'), ('TEAM', 'Equipe'), ('PRO', 'IA Pro')], default='trial', max_length=10),
        ),
    ]
