# Generated by Django 5.2.3 on 2026-01-30 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_barbershop_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='barbershop',
            name='onboarding_completed',
            field=models.BooleanField(default=False),
        ),
    ]
