# Generated by Django 5.2.3 on 2026-01-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_barbershop_onboarding_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='service',
        ),
        migrations.AddField(
            model_name='appointment',
            name='services',
            field=models.ManyToManyField(related_name='appointments', to='api.service'),
        ),
        migrations.AddField(
            model_name='service',
            name='buffer_time',
            field=models.IntegerField(default=0, help_text='Tempo de folga após o serviço em minutos'),
        ),
    ]
