# Generated by Django 5.2.3 on 2026-02-02 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_appointment_service_appointment_services_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='payment_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pendente'), ('WAITING_PAYMENT', 'Aguardando Pagamento'), ('PAID', 'Pago')], default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='barbershop',
            name='pix_key',
            field=models.CharField(blank=True, help_text='Chave Pix para recebimento', max_length=100, null=True),
        ),
    ]
