# Generated by Django 6.0.1 on 2026-02-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_appointment_payment_id_appointment_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='phone',
        ),
        migrations.AddField(
            model_name='appointment',
            name='client_phone',
            field=models.CharField(blank=True, help_text='Telefone do cliente (opcional)', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='barber',
            name='whatsapp',
            field=models.CharField(blank=True, help_text='Telefone com DDD (apenas números)', max_length=20, null=True),
        ),
    ]
