# Generated by Django 5.2.3 on 2026-03-13 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_barber_phone_appointment_client_phone_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='description',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='description',
        ),
        migrations.RemoveField(
            model_name='barbershop',
            name='instagram',
        ),
    ]
