# Generated by Django 5.2.3 on 2026-03-13 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_remove_barber_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
