# Generated by Django 5.2.3 on 2026-03-13 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_barber_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barber',
            name='description',
        ),
    ]
