# Generated by Django 5.2 on 2026-03-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_barber_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='barber',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
